# Generated by Django 4.1.5 on 2023-01-28 02:39

import cnab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=cnab.models.upload_to)),
            ],
        ),
    ]
