# Generated by Django 4.1.5 on 2023-01-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=80)),
                ('establishment', models.CharField(max_length=19)),
                ('type', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=17)),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=11)),
                ('hour', models.TimeField()),
                ('owner', models.CharField(max_length=14)),
            ],
        ),
    ]
